apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
   affinity:
     nodeAffinity:
     # hard rule 
       requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
         - matchExpressions:
           - key: topology.kubernetes.io/zone
             operator: In
             values:
             - us-east-1f
          #  - key: disktype
          #    operator: In
          #    values:
          #    - ssd
            # soft rule
       preferredDuringSchedulingIgnoredDuringExecution:
       - weight: 1
         preference:
           matchExpressions:
           - key: disktype
             operator: In
             values:
                         
   containers:
   - name: nginx
     image: nginx
     imagePullPolicy: Always
